name: Flask CI/CD with Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DEBUG: ${{ secrets.DEBUG }}
  MODEL_PATH: ${{ secrets.MODEL_PATH }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    

  docker-build:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image
      run: |
        docker build -t flask-ml-app .

    - name: Test Docker image
      run: |
        docker run -d -p 5000:5000 --name flask-ml-container flask-ml-app
        sleep 5
        curl --fail http://localhost:5000/api/health || exit 1
